# Generated by Django 5.2.13 on 2026-04-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='duration_seconds',
            new_name='duration_minutes',
        ),
    ]
