# Generated by Django 5.2.13 on 2026-04-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_rename_duration_seconds_exercise_duration_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselog',
            old_name='duration_seconds',
            new_name='duration_minutes',
        ),
    ]
