# Generated by Django 5.2.13 on 2026-04-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_rename_duration_seconds_exerciselog_duration_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
