# Generated by Django 5.2.13 on 2026-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
