# Generated by Django 5.2.13 on 2026-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_exercise_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('dumbbells', 'Dumbbells'), ('barbell', 'Barbell'), ('kettlebell', 'Kettlebell'), ('resistance_bands', 'Resistance Bands'), ('machine', 'Machine'), ('bicycle', 'Bicycle'), ('treadmill', 'Treadmill'), ('elliptical', 'Elliptical'), ('rowing_machine', 'Rowing Machine'), ('yoga_mat', 'Yoga Mat')], max_length=20, null=True),
        ),
    ]
