# Generated by Django 5.2.13 on 2026-05-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_alter_exercise_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='duration_minutes',
        ),
    ]
