# Generated by Django 5.2.13 on 2026-05-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_remove_exerciselog_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
