# Generated by Django 5.2.13 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0009_exerciselog_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
